---

- hosts: all
  become: true
  tasks:

  - name: update repository index  
    ansible.builtin.dnf:
      update_cache: yes

  - name: install apache2 package (httpd)
    ansible.builtin.dnf:
      name: httpd
      state: latest 

  - name: Enable and start Apache service
    ansible.builtin.service:
      name: httpd
      enabled: yes
      state: started


  - name: Open HTTP service in firewalld
    ansible.posix.firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes

  - name: installing php support for apache
    ansible.builtin.dnf:
      name: php
      state: latest

  - name: restart httpd
    ansible.builtin.systemd:
      name: httpd
      state: restarted
