---

- hosts: all
  become: true
  tasks:

  - name: update repository and install apache2 and php packages  
    package:
      update_cache: yes
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      
  - name: Enable and start Apache service
    ansible.builtin.service:
      name: "{{ apache_package }}"
      enabled: yes
      state: started

  - name: Open HTTP service in firewalld RedHat
    ansible.posix.firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes
    when: ansible_facts['distribution'] == "RedHat"

  - name: Open HTTP service in ufw Ubuntu
    community.general.ufw:
      rule: allow
      name: "Apache Full"
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: Ensure UFW is enabled Ubuntu
    community.general.ufw:
      state: enabled
    when: ansible_facts['distribution'] == "Ubuntu"

 
