---

- hosts: all
  become: true
  tasks:

  - name: removing apache (httpd) and php packages
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent 
