---

- hosts: all
  become: true
  pre_tasks:

  - name: Update repo
    tags: always
    package:
      update_cache: yes
    changed_when: false

- hosts: all
  become: true
  roles:
    - base

- hosts: workstations
  become: true
  vars_files:
    - vault.yml
  roles: 
    - workstations

- hosts: webservers
  become: true
  roles: 
    - web_servers
  
- hosts: dbservers
  become: true
  roles:
    - db_servers

- hosts: fileservers
  become: yes
  roles:
    - file_servers
